version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - make html-noplot

sphinx:
  builder: html-noplot
  configuration: docs/source/conf.py

python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
